sudo: required

language: node_js
node_js:
  - "6.5"

addons:
  postgresql: "9.4"

before_script:
  - psql -c 'create database okcollege_dev;' -U postgres
  - wget -r https://raw.githubusercontent.com/rpiml/okcollege-dev/master/assets/ -P ./assets
  - npm install -g gulp

script:
- gulp test
